"""
Генератор схемы кудитного QAOA в формате OpenQASM 2.0.

Схема пригодна для загрузки в текстовый редактор страницы «Квантовые
вычисления» ОПКВ (вкладка QASM) и для запуска на любом сервисе, который
принимает QASM-схему: ideem_ideal_30, ideem_noisy_30, Qiskit Aer Simulator IBM,
SpinQ Triangulum, Superconducting Qubits MISIS, Atom MSU, IQC Yb+/Ca+ RQC.

Используются только вентили стандартной библиотеки qelib1.inc, входящие
в перечень вентилей графического редактора платформы (Таблица 2 руководства):
x, h, rx, ry, rz, u1, u3, cx, barrier, measure. Многоуправляемые вентили
не требуются: в позиционном кодировании все слагаемые целевой функции
не более чем двухлокальны.

Структура схемы:

    1. Блок инициализации состояний кубитов в формате, который использует
       графический редактор платформы (u3(0,0,0) + barrier) — благодаря
       этому текстовый и графический редакторы синхронизируются.
    2. Подготовка равномерной суперпозиции по уровням каждого кудита
       (состояние типа W на его one-hot кубитах).
    3. p слоёв: фазовый оператор exp(-i γ C) и кудитный смеситель.
    4. Измерение всех кубитов в классический регистр.
"""

from __future__ import annotations

from math import acos, pi, sqrt
from typing import Sequence

from ..formulation.qudo_model import QUDOModel
from ..model.qudit import QUDIT
from .mixer import mixer_edges


class QasmProgram:
    """Накопитель строк QASM."""

    def __init__(self) -> None:
        self.lines: list[str] = []

    def add(self, line: str) -> None:
        self.lines.append(line)

    def comment(self, text: str) -> None:
        self.lines.append(f"// {text}")

    def blank(self) -> None:
        self.lines.append("")

    def text(self) -> str:
        return "\n".join(self.lines) + "\n"

    # --- элементарные вентили qelib1.inc ------------------------------

    def x(self, qubit: int) -> None:
        self.add(f"x q[{qubit}];")

    def h(self, qubit: int) -> None:
        self.add(f"h q[{qubit}];")

    def rx(self, angle: float, qubit: int) -> None:
        self.add(f"rx({_angle(angle)}) q[{qubit}];")

    def ry(self, angle: float, qubit: int) -> None:
        self.add(f"ry({_angle(angle)}) q[{qubit}];")

    def rz(self, angle: float, qubit: int) -> None:
        self.add(f"rz({_angle(angle)}) q[{qubit}];")

    def u1(self, angle: float, qubit: int) -> None:
        self.add(f"u1({_angle(angle)}) q[{qubit}];")

    def cx(self, control: int, target: int) -> None:
        self.add(f"cx q[{control}],q[{target}];")

    def barrier(self) -> None:
        self.add("barrier q;")

    # --- составные операции -------------------------------------------

    def cry(self, angle: float, control: int, target: int) -> None:
        """Управляемый поворот ry через ry/cx."""

        self.ry(angle / 2.0, target)
        self.cx(control, target)
        self.ry(-angle / 2.0, target)
        self.cx(control, target)

    def cphase(self, angle: float, control: int, target: int) -> None:
        """Управляемый фазовый сдвиг через u1/cx."""

        self.u1(angle / 2.0, control)
        self.cx(control, target)
        self.u1(-angle / 2.0, target)
        self.cx(control, target)
        self.u1(angle / 2.0, target)

    def rxx(self, angle: float, left: int, right: int) -> None:
        self.h(left)
        self.h(right)
        self.cx(left, right)
        self.rz(angle, right)
        self.cx(left, right)
        self.h(left)
        self.h(right)

    def ryy(self, angle: float, left: int, right: int) -> None:
        self.rx(pi / 2.0, left)
        self.rx(pi / 2.0, right)
        self.cx(left, right)
        self.rz(angle, right)
        self.cx(left, right)
        self.rx(-pi / 2.0, left)
        self.rx(-pi / 2.0, right)

    def xy(self, beta: float, left: int, right: int) -> None:
        """exp(-i β (XX + YY) / 2) — «перескок» между уровнями кудита."""

        self.rxx(beta, left, right)
        self.ryy(beta, left, right)


def _angle(value: float) -> str:
    return f"{float(value):.10f}"


def build_qaoa_qasm(
    model: QUDOModel,
    gammas: Sequence[float],
    betas: Sequence[float],
    measure: bool = True,
    header: Sequence[str] = (),
) -> str:
    """Собирает схему QAOA с заданными параметрами."""

    if len(gammas) != len(betas):
        raise ValueError("Число параметров γ и β должно совпадать.")

    layout = model.layout
    program = QasmProgram()

    program.comment("Generated by QUDO launcher for the quantum cloud platform")
    program.comment("Кудитный QAOA: размещение виртуальных машин по физическим хостам")
    for line in header:
        program.comment(line)
    program.comment(f"layers p = {len(gammas)}")
    program.comment("gamma = [" + ", ".join(f"{float(g):.6f}" for g in gammas) + "]")
    program.comment("beta  = [" + ", ".join(f"{float(b):.6f}" for b in betas) + "]")
    program.comment(f"coefficient scale = {model.scale:.6f}")
    program.blank()

    program.add("OPENQASM 2.0;")
    program.add('include "qelib1.inc";')
    program.blank()

    size = layout.n_vars
    program.add(f"qreg q[{size}];")
    program.add(f"creg c[{size}];")
    program.blank()

    # Блок начальных состояний в формате графического редактора платформы.
    program.comment("Qubits initional states. Begin")
    for qubit in range(size):
        program.add(f"u3(0, 0, 0) q[{qubit}];")
    program.barrier()
    program.comment("Qubits initional states. End")
    program.blank()

    # Равномерная суперпозиция по уровням кудитов.
    program.comment("Начальное состояние: равномерная суперпозиция уровней кудитов")
    for register in layout.registers:
        qubits = list(register.var_indices())
        if register.kind == QUDIT:
            _prepare_uniform_onehot(program, qubits)
        else:
            program.h(qubits[0])
    program.barrier()
    program.blank()

    scale = model.scale if model.scale else 1.0

    for layer, (gamma, beta) in enumerate(zip(gammas, betas)):
        program.comment(f"Слой {layer + 1}: фазовый оператор exp(-i*gamma*C)")
        for var, weight in sorted(model.linear.items()):
            angle = -float(gamma) * float(weight) / scale
            if angle:
                program.u1(angle, var)

        for (left, right), weight in sorted(model.quadratic.items()):
            angle = -float(gamma) * float(weight) / scale
            if angle:
                program.cphase(angle, left, right)

        program.barrier()

        program.comment(f"Слой {layer + 1}: кудитный смеситель (XY на кольце уровней)")
        for register in layout.registers:
            qubits = list(register.var_indices())
            if register.kind == QUDIT:
                for left, right in mixer_edges(register.dim):
                    program.xy(float(beta), qubits[left], qubits[right])
            else:
                program.rx(2.0 * float(beta), qubits[0])

        program.barrier()
        program.blank()

    if measure:
        program.comment("Измерение: позиция единицы в блоке кудита = номер хоста")
        for qubit in range(size):
            program.add(f"measure q[{qubit}] -> c[{qubit}];")

    return program.text()


def _prepare_uniform_onehot(program: QasmProgram, qubits: list[int]) -> None:
    """
    Готовит состояние (|10...0> + |01...0> + ... + |0...01>) / sqrt(d).

    Каскад ry/cx: на шаге k амплитуда переносится с предыдущего кубита
    на следующий в отношении 1 : (d - k).
    """

    dim = len(qubits)
    if dim == 0:
        return

    program.x(qubits[0])

    for k in range(1, dim):
        theta = 2.0 * acos(sqrt(1.0 / (dim - k + 1)))
        program.cry(theta, qubits[k - 1], qubits[k])
        program.cx(qubits[k], qubits[k - 1])


def circuit_statistics(text: str) -> dict:
    """
    Считает характеристики схемы: число вентилей по типам и оценку глубины.

    Нужны, чтобы заранее сопоставить схему с ограничениями выбранного
    сервиса платформы (число кубитов, длина схемы).
    """

    counts: dict[str, int] = {}
    qubits = 0
    layers_busy: dict[int, int] = {}
    depth = 0

    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue

        if line.startswith("qreg"):
            qubits = int(line.split("[")[1].split("]")[0])
            continue

        if line.startswith(("OPENQASM", "include", "creg")):
            continue

        name = line.split("(")[0].split(" ")[0].split(";")[0]
        counts[name] = counts.get(name, 0) + 1

        if name in ("barrier", "measure"):
            continue

        targets = [
            int(token.split("[")[1].split("]")[0])
            for token in line.split(" ", 1)[-1].replace(";", "").split(",")
            if "[" in token
        ]
        if targets:
            start = max(layers_busy.get(target, 0) for target in targets)
            for target in targets:
                layers_busy[target] = start + 1
            depth = max(depth, start + 1)

    return {
        "qubits": qubits,
        "gates_total": sum(value for key, value in counts.items() if key not in ("barrier",)),
        "two_qubit_gates": counts.get("cx", 0),
        "depth_estimate": depth,
        "by_gate": counts,
    }
